# Generated by Django 3.2.9 on 2021-12-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('motivation', models.CharField(choices=[('Vacation', 'Vacation'), ('Holiday', 'Holiday'), ('Sick', 'Sick')], max_length=60)),
                ('send_mail', models.BooleanField(default=True)),
            ],
        ),
    ]
